services:
  monday-webapi:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: webapi
    image: mojski/monday-webapi:latest
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    restart: unless-stopped